name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend-tests:
    strategy:
      matrix:
        service: [auth_service, user_service]
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/backend/${{ matrix.service }}
      SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.TEST_SUPABASE_KEY }}
      JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd backend/${{ matrix.service }}
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install fastapi uvicorn
    - name: Run tests
      run: |
        cd backend/${{ matrix.service }}
        pytest tests/ --cov=. --cov-report=xml
    
  frontend-tests:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    - name: Run tests
      run: |
        cd frontend
        npm run test
